# Generated by Django 3.1.7 on 2021-04-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_keeper_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='app_user',
        ),
    ]
