# Generated by Django 3.1.7 on 2021-04-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_keeper_app', '0004_auto_20210413_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
