# Generated by Django 3.1.7 on 2021-04-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_keeper_app', '0006_auto_20210413_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=200),
        ),
    ]
